2020-07-30 20:47:59,215 ERROR [8] CommonHelpers.Helpers.LogError - Event Error
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 172.217.163.42:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at EventManagement.BusinessLogic.Business.GoogleDriveSync.CallApi(String jsonkeysfilepath, String filename) in D:\Galactic DEV _06 TFS\Galactic\Event Application\CMS App\Dev\UI\EventManagementPortal-main\EventManagement.BusinessLogic\Business\GoogleDriveSync.cs:line 384
   at EventManagement.Controllers.EventsController.<Create>d__48.MoveNext() in D:\Galactic DEV _06 TFS\Galactic\Event Application\CMS App\Dev\UI\EventManagementPortal-main\EventManagement\Controllers\EventsController.cs:line 956
2020-07-30 21:02:29,917 ERROR [25] CommonHelpers.Helpers.LogError - Event Error
EventManagement.BusinessLogic.Classes.GalacticEventExistsException: Event with Galactic id already exist
   at EventManagement.BusinessLogic.Business.EventLogic.<AddUpdateEvent>d__20.MoveNext() in D:\Galactic DEV _06 TFS\Galactic\Event Application\CMS App\Dev\UI\EventManagementPortal-main\EventManagement.BusinessLogic\Business\EventLogic.cs:line 629
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EventManagement.Controllers.EventsController.<Create>d__48.MoveNext() in D:\Galactic DEV _06 TFS\Galactic\Event Application\CMS App\Dev\UI\EventManagementPortal-main\EventManagement\Controllers\EventsController.cs:line 954
2020-07-30 21:02:30,131 ERROR [17] CommonHelpers.Helpers.LogError - Event Error
EventManagement.BusinessLogic.Classes.GalacticEventExistsException: Event with Galactic id already exist
   at EventManagement.BusinessLogic.Business.EventLogic.<AddUpdateEvent>d__20.MoveNext() in D:\Galactic DEV _06 TFS\Galactic\Event Application\CMS App\Dev\UI\EventManagementPortal-main\EventManagement.BusinessLogic\Business\EventLogic.cs:line 629
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EventManagement.Controllers.EventsController.<Create>d__48.MoveNext() in D:\Galactic DEV _06 TFS\Galactic\Event Application\CMS App\Dev\UI\EventManagementPortal-main\EventManagement\Controllers\EventsController.cs:line 954
2020-07-30 21:02:30,937 ERROR [29] CommonHelpers.Helpers.LogError - Event Error
EventManagement.BusinessLogic.Classes.GalacticEventExistsException: Event with Galactic id already exist
   at EventManagement.BusinessLogic.Business.EventLogic.<AddUpdateEvent>d__20.MoveNext() in D:\Galactic DEV _06 TFS\Galactic\Event Application\CMS App\Dev\UI\EventManagementPortal-main\EventManagement.BusinessLogic\Business\EventLogic.cs:line 629
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EventManagement.Controllers.EventsController.<Create>d__48.MoveNext() in D:\Galactic DEV _06 TFS\Galactic\Event Application\CMS App\Dev\UI\EventManagementPortal-main\EventManagement\Controllers\EventsController.cs:line 954
